export const TYPES = {
    // AUTH
	SET_AUTH_TOKEN: 'SET_AUTH_TOKEN',
    // DATA
	FETCHING_COMPLETE: 'FETCHING_COMPLETE',
	RESET_FETCHING: 'RESET_FETCHING',
    // USER
	GET_USER_INFO: 'GET_USER_INFO',
	UPDATE_USER: 'UPDATE_USER',
	UPDATE_USER_DOORS: 'UPDATE_USER_DOORS',
	RESET_USER: 'RESET_USER',
    // HEADER AND NAVIGATION
	TOGGLE_MENU: 'TOGGLE_MENU',
    // DOORS/LOCKS LIST
	CHANGE_LIST_FILTER: 'CHANGE_LIST_FILTER',
	TOGGLE_LOCK: 'TOGGLE_LOCK',
	SHOW_LOCK: 'SHOW_LOCK',
	HIDE_LOCK: 'HIDE_LOCK',
	RESET_LOCK: 'RESET_LOCK',
	CHANGE_LOCK_STATUS: 'CHANGE_LOCK_STATUS',
	UNLOCK_DOOR: 'UNLOCK_DOOR',
	REQUEST_ACCESS: 'REQUEST_ACCESS',
    // ADMIN SETTINGS: DOORS
	GET_DOOR_LIST: 'GET_DOOR_LIST',
	TOGGLE_DOOR: 'TOGGLE_DOOR',
	SHOW_DOOR: 'SHOW_DOOR',
	HIDE_DOOR: 'HIDE_DOOR',
	RESET_DOOR: 'RESET_DOOR',
	CHANGE_DOOR_STATUS: 'CHANGE_DOOR_STATUS',
	UPDATE_DOOR_EMPLOYEES: 'UPDATE_DOOR_EMPLOYEES',
	UPDATE_DOOR_NAME: 'UPDATE_DOOR_NAME',
	ADD_DOOR: 'ADD_DOOR',
	UPDATE_DOOR: 'UPDATE_DOOR',
	// ADMIN SETTINGS: EMPLOYEES
	GET_EMPLOYEE_LIST: 'GET_EMPLOYEE_LIST',
	TOGGLE_EMPLOYEE: 'TOGGLE_EMPLOYEE',
	SHOW_EMPLOYEE: 'SHOW_EMPLOYEE',
	HIDE_EMPLOYEE: 'HIDE_EMPLOYEE',
	RESET_EMPLOYEE: 'RESET_EMPLOYEE',
	CHANGE_EMPLOYEE_STATUS: 'CHANGE_EMPLOYEE_STATUS',
	UPDATE_EMPLOYEE_DOORS: 'UPDATE_EMPLOYEE_DOORS',
	UPDATE_EMPLOYEE_NAME: 'UPDATE_EMPLOYEE_NAME',
	ADD_EMPLOYEE: 'ADD_EMPLOYEE',
	UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
    // ADMIN SETTINGS: EVENTS
	GET_EVENTS_LIST: 'GET_EVENTS_LIST',
	UPDATE_EVENTS_LIST: 'UPDATE_EVENTS_LIST',
	CHANGE_EVENT_FILTER: 'CHANGE_EVENT_FILTER',
	ADD_EVENT: 'ADD_EVENT',
}
